### ISSUE TITLE
Create data resource for cancer incidence and mortality broken down by ....

### ISSUE THREAD

**Issue by seandavi** [colorado-cancer-center/ecco#14]
I'm getting data on incidence and mortality broken down by below. The data will be available as a long-form table (should be a few million rows). I'll share when I'm done. The data look like:

|          County          |  FIPS  | Age-Adjusted_Incidence_Raterate_note_-_cases_per_100,000 | Lower_95%_Confidence_Interval | Upper_95%_Confidence_Interval | CI_Rankrank_note | Lower_CI_CI_Rank | Upper_CI_CI_Rank | Average_Annual_Count | Recent_Trend | Recent_5-Year_Trend_trend_note_in_Incidence_Rates | Lower_95%_Confidence_Interval.1 | Upper_95%_Confidence_Interval.1 | year | stateFIPS | sex | stage | race | cancer | area_type | age |
|--------------------------|--------|----------------------------------------------------------|-------------------------------|-------------------------------|------------------|------------------|------------------|----------------------|--------------|---------------------------------------------------|---------------------------------|---------------------------------|------|-----------|-----|-------|------|--------|-----------|-----|
| Alameda County(7)        | 6001.0 | 371.5                                                    | 367.5                         | 375.5                         | 47               |  41              |  51              | 6890.0               | falling      | -1.4                                              | -2.6                            |  -1.0                           | 0    | 08        | 0   | 999   | 38   | 076    | county    | 009 |
| Modoc County(7)          | 6049.0 | 310.6                                                    | 266.1                         | 361.2                         | 55               |  39              |  58              | 44.0                 | stable       | -1.4                                              | -3.4                            |  0.5                            | 0    | 08        | 1   | 999   | 48   | 090    | county    | 136 |
| Butte County(7)          | 6007.0 | 474.9                                                    | 463.0                         | 486.9                         | 3                |  1               |  6               | 1347.0               | falling      | -0.5                                              | -0.9                            |  -0.1                           | 0    | 08        | 2   | 211   | 28   | 057    | county    | 009 |
| Alameda County(7)        | 6001.0 | 371.5                                                    | 367.5                         | 375.5                         | 47               |  41              |  51              | 6890.0               | falling      | -1.4                                              | -2.6                            |  -1.0                           | 0    | 08        | 0   | 211   | 48   | 001    | county    | 157 |
| Humboldt County(7)       | 6023.0 | 435.8                                                    | 421.4                         | 450.7                         | 12               |  4               |  23              | 755.0                | falling      | -1.0                                              | -1.5                            |  -0.4                           | 0    | 08        | 2   | 211   | 07   | 066    | county    | 157 |
| Riverside County(7)      | 6065.0 | 389.6                                                    | 386.2                         | 393.0                         | 35               |  31              |  42              | 10550.0              | falling      | -0.8                                              | -1.0                            |  -0.7                           | 0    | 08        | 0   | 211   | 07   | 053    | county    | 009 |
| Stanislaus County(7)     | 6099.0 | 422.3                                                    | 414.6                         | 430.0                         | 16               |  12              |  25              | 2390.0               | stable       | -0.2                                              | -0.5                            |  0.1                            | 0    | 08        | 2   | 211   | 05   | 057    | county    | 001 |
| San Bernardino County(7) | 6071.0 | 393.8                                                    | 390.0                         | 397.7                         | 34               |  29              |  39              | 8326.0               | falling      | -0.8                                              | -1.0                            |  -0.6                           | 0    | 08        | 1   | 999   | 05   | 090    | county    | 006 |
| Nevada County(7)         | 6057.0 | 402.4                                                    | 387.6                         | 417.6                         | 29               |  15              |  41              | 694.0                | falling      | -1.3                                              | -1.9                            |  -0.7                           | 0    | 08        | 1   | 211   | 48   | 080    | county    | 157 |
| Marin County(7)          | 6041.0 | 442.0                                                    | 432.3                         | 451.9                         | 9                |  5               |  15              | 1754.0               | falling      | -0.6                                              | -0.9                            |  -0.4                           | 0    | 08        | 2   | 999   | 38   | 020    | county    | 136 |
| Glenn County(7)          | 6021.0 | 509.8                                                    | 475.3                         | 546.2                         | 1                |  1               |  5               | 170.0                | stable       | 0.2                                               | -0.6                            |  1.1                            | 0    | 08        | 1   | 999   | 07   | 090    | county    | 009 |
| Lassen County(7)         | 6035.0 | 346.7                                                    | 319.0                         | 376.2                         | 53               |  35              |  57              | 122.0                | stable       | 0.3                                               | -0.8                            |  1.6                            | 0    | 08        | 2   | 211   | 28   | 035    | county    | 009 |
| Marin County(7)          | 6041.0 | 442.0                                                    | 432.3                         | 451.9                         | 9                |  5               |  15              | 1754.0               | falling      | -0.6                                              | -0.9                            |  -0.4                           | 0    | 08        | 2   | 999   | 38   | 515    | county    | 001 |
| Alameda County(7)        | 6001.0 | 371.5                                                    | 367.5                         | 375.5                         | 47               |  41              |  51              | 6890.0               | falling      | -1.4                                              | -2.6                            |  -1.0                           | 0    | 08        | 2   | 211   | 38   | 090    | county    | 136 |
| Solano County(7)         | 6095.0 | 415.6                                                    | 407.7                         | 423.6                         | 21               |  14              |  30              | 2228.0               | falling      | -1.5                                              | -2.5                            |  -1.0                           | 0    | 08        | 1   | 999   | 48   | 055    | county    | 009 |
| Sacramento County(7)     | 6067.0 | 412.3                                                    | 407.9                         | 416.7                         | 22               |  18              |  28              | 7022.0               | falling      | -1.3                                              | -1.8                            |  -1.1                           | 0    | 08        | 1   | 211   | 07   | 400    | county    | 001 |
| Napa County(7)           | 6055.0 | 410.5                                                    | 397.3                         | 424.1                         | 24               |  13              |  37              | 776.0                | falling      | -2.6                                              | -4.0                            |  -1.7                           | 0    | 08        | 1   | 211   | 28   | 040    | county    | 136 |
| Mono County(7)           | 6051.0 | 250.6                                                    | 217.8                         | 287.4                         | 58               |  55              |  58              | 47.0                 | stable       | -1.2                                              | -3.4                            |  1.3                            | 0    | 08        | 1   | 999   | 05   | 076    | county    | 157 |
| Glenn County(7)          | 6021.0 | 509.8                                                    | 475.3                         | 546.2                         | 1                |  1               |  5               | 170.0                | stable       | 0.2                                               | -0.6                            |  1.1                            | 0    | 08        | 2   | 211   | 38   | 047    | county    | 001 |
| San Diego County(7)      | 6073.0 | 418.5                                                    | 415.5                         | 421.5                         | 18               |  15              |  24              | 15343.0              | rising       | 1.1                                               | 0.3                             |  1.7                            | 0    | 08        | 2   | 211   | 48   | 053    | county    | 006 |

**Comment by falquaddoomi** [comment]
Related to #30, derived from #16.
