### ISSUE TITLE
Scrape state cancer profiles

### ISSUE THREAD

**Issue by seandavi** [colorado-cancer-center/ecco#16]
https://gist.github.com/seandavi/3d3136aaf66b0b58e2f1906085415312

**Comment by falquaddoomi** [comment]
Required for #30.

Need to integrate this into the data fetching pipeline.

**Comment by vincerubinetti** [comment]
Was this closed as part of #38?

**Comment by falquaddoomi** [comment]
> Was this closed as part of #38?

No, and I apologize for the confusion; my comment above about it being related to #30 is incorrect. This the dataset described in issue #14; it comes from a different source than CancerInFocus, https://statecancerprofiles.cancer.gov. It includes more comprehensive stratification options than the CancerInFocus dataset from issue #30, which just includes sex and ethnicity as options.
