### ISSUE TITLE
ETL data from cancerinfocus.org

### ISSUE THREAD

**Issue by seandavi** [colorado-cancer-center/ecco#2]
The data for CancerInFocus are available for the entire US as a Zip from here:

![image](https://github.com/colorado-cancer-center/COCancerScope/assets/92435/a16a7f05-b750-41f2-9090-babfc854d6b2)

I suspect that the download URL may change over time, so scraping to get the URL may be required. You'll get multiple "grains" of data (state, county, etc.). There is also a "long" and "wide" version for each resource.

**Comment by falquaddoomi** [comment]
Thanks, that's helpful. Just FYI, I'm currently pulling this archive, using just the "long" tables, and filtering them on the state columns to just "Colorado": https://cancerinfocus.org/public-data/Current/us.zip. I'm still working on a robust version of the ETL code; expect that in a future PR that should close this issue.

Regarding generalizing this to other states: there's currently a setting in the `settings.py` module that specifies the state by which to filter, which I'll likely pull out as an environment variable. I assume whoever wants to use it for another state will bring their own county and tract boundaries in an `ogr2ogr`-compatible format (GeoJSON is the least fussy). At the moment I hardcoded the geometry loading step to load from files with "Colorado" in the name, but there's no reason that those filenames can't also be pulled out as an env vars, too.

**Comment by falquaddoomi** [comment]
Todo, add to dagster download pipeline.

**Comment by falquaddoomi** [comment]
This issue's original goal is IMO complete. My last comment is more appropriately captured by issue #74.
