### ISSUE TITLE
[New Data] Cancer Disparities Index

### ISSUE THREAD

**Issue by seandavi** [colorado-cancer-center/ecco#27]
### Name

Cancer Disparities Index

### URL

https://cohealthviz.dphe.state.co.us/t/HSEBPublic/views/CCPDDiseaseDisparityCountyIndexRanking/CCPDRankings?%3Aembed=y&%3Adisplay_count=no

### Description

As I understand it, the Colorado Department of Public Health and Environment (CDPHE) used a PCA-based approach to come up with health disparities indices. A high-level description is available here: <https://cohealthviz.dphe.state.co.us/t/HSEBPublic/views/CCPDDiseaseDisparityCountyIndexRanking/CCPDRankings?%3Aembed=y&%3Adisplay_count=no>

### Relevance

```markdown
The idea is to provide a map of that highlights disparities at the county level.
```

### Anything else?

This is an Excel file prepared by Amy Mellies when she was working in PHSR with COE that includes similar information to that available from the CDPHE website. 

[DT-COE Cancer Disparity Indices and Treatment Locations by County.xlsx](https://github.com/colorado-cancer-center/COCancerScope/files/13663936/DT-COE.Cancer.Disparity.Indices.and.Treatment.Locations.by.County.xlsx)

**Comment by seandavi** [comment]
It isn't clear that these are the most updated values, but it seems from previous communications that plotting based on "rank" of counties (or, equivalently, quintiles) of some rank is the likely target format of the data.

**Comment by cydneyj303** [comment]
The index is a different measure than what is currently presented in ECCO; it's a ranking, not a count or %. We need some time to thoroughly think about how to present this and provide context for public use. If the team has some ideas, we'd love to hear them.

**Comment by seandavi** [comment]
I'd suggest presenting the data as is (ranks); ranks are pretty easy to understand. The user interface will take care of coloring.

**Comment by falquaddoomi** [comment]
From the meeting:

Measure Category: Disparity Index
Measure: Cancer Site (Head/Neck, Breast, Lung, Colorectal)
