### ISSUE TITLE
Map, scale colors are inconsistent across geographies, measures

### ISSUE THREAD

**Issue by falquaddoomi** [colorado-cancer-center/ecco#49]
From Jan (paraphrased): It can be disorienting to see the colors change as you select different measure categories, measures, and geographic groupings (county vs. tract). Since the colors depend on the dataset, you can't use specific colors as a means to compare across different measures.

Background: The map colors are generated by taking the minimum and maximum values (aka the "extent") of the currently-visible dataset, then generating a set number of steps between. Some measures are percentages, while others are literal values.

Options:
- scale each measure separately across its county and tract values
  - issues: doesn't provide color consistency across measures
- find a global min, max across all measures
  - issues: wouldn't work well for percentages vs literal values
- allow the user to specify that they want an absolute scale, and then to specify the min and max values for that scale
  - issues: user might become disoriented switching between, e.g. percentages vs. literals, or measures with wildly different extents
  
 Some things that would help flesh out this issue and make it more concrete:
- [ ] examples of pairs of measures where the difference is extreme
- [ ] user stories, i.e. specific users who would want this feature
- [ ] other options on how to present the data

**Comment by vincerubinetti** [comment]
This is my gut feeling on this:

The behavior we have now should remain the default behavior. I think it's natural and expected that if you change a measure (or any other "input"), the map/scale visibly changes. It's different data. We're talking about catering to a narrower scenario (I think) in which someone is switching from one measure to a directly related one -- for example black vs. white cancer incidence -- and seeing the difference. That said, I still think this is a good option to have somehow, especially given the key nature of that example. Regardless of the solution we choose, I think the behavior should be **opt-in** by the user, so they're aware they've done something that might prevent them from seeing data properly.

I'm leaning toward the following solution:

Have two number boxes above the "More Options" called "Min/max". They start off in "automatic" mode where they reflect the true min/max range of the selected data. Once the user edits one or both of them, though, they set them to "manual" mode, and a little button appears next to them to reset to auto, and they will not change until the user clicks that.

I feel that we should not get into the hairiness that arises from trying to "smartly" figure out what the "global" range should be for the measure the user is viewing. Not only are there different types of values (%s vs. per 100k vs. absolute count vs. rankings), but there are different subjective groupings (e.g., perhaps "asthma" and "binge drink" shouldn't share the same min/max, even though they are both risk factors and %s, for some ideological reason). Unless someone can come up with a simple and consistent way to make it clear to the user (and ourselves) -- e.g. the range will always be global to the measure _category_, and if you change the selected category the range should change -- we should probably not do this.

**Comment by janolowery** [comment]
This sounds reasonable, Vince.   Lets keep as is for now.  We can consider changing after getting broader feedback if needed.
Thank you for weighing in.
