### ISSUE TITLE
Add descriptions for each measure, measure category

### ISSUE THREAD

**Issue by falquaddoomi** [colorado-cancer-center/ecco#54]
Currently, measures and measure categories like the Cancer Disparity Index are a bit opaque: it's unclear what the measure means. It would be good to have a simple description of measures that might be confusing, and more text (perhaps on a separate "glossary" page) that more fully describes the measure.

We'll likely display the short explanation in the "no data" explanation box, possibly with a link to the longer description on the "glossary" page.

Todo:
- [ ] disparity measures writeup, social vs. cancer incidence/mortality
- [ ] add other measures that we want to describe in detail

**Comment by cydneyj303** [comment]
Hi all - 
These descriptions are what we'll include in ECCO for now. As pop-up such as the "no data" box works great, or however you think this would look best. Based on feedback we receive, we might be adding to this in the future but this should provide some context for the time being. Thanks.

[MeasureDescriptions.docx](https://github.com/colorado-cancer-center/ecco/files/15000406/MeasureDescriptions.docx)
