### ISSUE TITLE
Default age category is <50 - change to "all ages"

### ISSUE THREAD

**Issue by cydneyj303** [colorado-cancer-center/ecco#66]
<img width="864" alt="image" src="https://github.com/colorado-cancer-center/ecco/assets/139499061/7905d7c2-00a0-4992-81da-46fd190e507a">

Hi -

I'm noticing that when I populate the incidence and mortality, the default age is "<50". Is it possible to change this to "All Ages"? Don't know if this is only on my end but hoping ya'll could double-check. Thanks!

**Comment by falquaddoomi** [comment]
Hey @cydneyj303, it's not just on your end, and sure, we'll address it ASAP. Thanks for the report!

**Comment by vincerubinetti** [comment]
Closed by #67
