### ISSUE TITLE
Description of the measurements

### ISSUE THREAD

**Issue by etiennedanis** [colorado-cancer-center/ecco#70]
Hello,
Great dataset!
After selecting the environment category, you can select different measurements:
pct5G_35_3, 
pct5G_7_1, 
pctBB_1000_10, 
pctBB_100_20.
What do they all mean?
Thank you very much in advance!
Best,
Etienne

**Comment by falquaddoomi** [comment]
Hi @etiennedanis; thanks for your issue report! I believe those measurements were recently introduced, and apparently we missed adding human-readable labels for them. We'll be adding the missing labels to the site ASAP; here are the labels we'll be adding for your reference:

- **pct5G_35_3:** Area with 35/3 Mbps Mobile 5G Coverage
- **pct5G_7_1:** Area with 7/1 Mbps Mobile 5G Coverage
- **pctBB_100_20:** Housing Units with 100/20 Mbps Broadband Service
- **pctBB_1000_10:** Housing Units with 1000/10 Mbps Broadband Service

(All the measures are percentages, and the speeds are written as `<downstream speed>`/`<upstream speed>`.)
