### ISSUE TITLE
Add legislative maps

### ISSUE THREAD

**Issue by falquaddoomi** [colorado-cancer-center/ecco#75]
From Jake Walsh's email:
> The second idea is adding the state legislative maps to ECCO. The maps would be put under the Locations menu and a user could select either the state House of Representatives or state Senate map. The selected map would then be overlayed over either the county or census tract maps. I already have the shapefiles for both district maps and an Excel sheet that has all of the legislators' names and contact information. I just want to see if it's possible to import these maps and overlay them in ECCO.

Since as Jake mentioned we don't have much data on a district level, there's no reason for it to be a geometry type alongside the county and tract maps. Essentially, the district regions *are* the data and should be superimposed over a selected measure for a county or tract.

Data required for implementation:
- shapefiles of the district maps
- spreadsheet with additional information for each district, e.g. the representative's name and contact info (displayed in a popup for the region)

**Comment by JWalsh75** [comment]
[2021_Approved_House_Plan_w_Final_Adjustments.zip](https://github.com/user-attachments/files/15942023/2021_Approved_House_Plan_w_Final_Adjustments.zip)
[2021_Approved_Senate_Plan_w_Final_Adjustments.zip](https://github.com/user-attachments/files/15942024/2021_Approved_Senate_Plan_w_Final_Adjustments.zip)
[Colorado State Representatives(Sheet1).csv](https://github.com/user-attachments/files/15942040/Colorado.State.Representatives.Sheet1.csv)

The two zip files contain folders with all of the shapefiles for both district maps. I also added an excel file that has all of the legislators' names, their districts, and their contact information. Some of the information on the excel sheet might have to be updated after the state elections but it's good enough for now.

**Comment by falquaddoomi** [comment]
@JWalsh75 Excellent, thank you! I was able to convert the house and senate shapefiles to GeoJSON, i.e. the format we use in the web app, without any issues; I visualized them as well and they appear to match up to the legislative boundaries I found on another resource. Both the house and senate maps' geometries were annotated with their district number, so that should be sufficient to join them to your CSV.

Regarding the updated information, do you think https://leg.colorado.gov/legislators would be a good source? It seems to contain the same data as your CSV; we could pull from it in our regular data updating pipeline. Let me know if you have another source that you'd prefer we use.

**Comment by vincerubinetti** [comment]
To get ahead of this, I started #81 which sets up the frontend to be able to show "area" locations in addition to the "point" locations that are already there.

At the moment, it's just hard-coding the data you provided into the frontend. @falquaddoomi feel free to work off of that PR to add this stuff to the backend. And perhaps you might want to move the "point" locations to the backend at the same time too #77.
