### ISSUE TITLE
Add state-level data number

### ISSUE THREAD

**Issue by vincerubinetti** [colorado-cancer-center/ecco#78]
Some quotes from Teams chat:

> [6/13 3:55 PM] Lowery, Jan
Hi All, a few updates and requests:  we shared ECCO with our Community Advisory Council last month and asked for feedback.  So far, only 10 people have filled out our feedback survey.  hoping we get more.  .......... We also heard from a few folks that they want to see Colorado data - so cancer incidence/mortality for Colorado as a whole - I believe the Profiles data has this, question is how to display on map?  Maybe within legend?  or maybe separate box? This applies to cancer rates and also risk factors, e.g. smoking prevalence, % of people up to date with screening. Any ideas on this?

> [6/13 7:39 PM] Rubinetti, Vincent
regarding the state-wide info. if i'm understanding correctly, this would basically just be a single number for the currently selected measure? e.g. sociodemographics -> total population would show a single number for the entire population of colorado? if so, yeah we'd probably just put that total right in one of the legends. if you go into "customization" and check "extra info", another legend pops up with min/max/avg/etc. we could add "total" or "overall" to that. i'd also have "extra info" checked by default then.
 like 2
[6/13 7:43 PM] Rubinetti, Vincent
for some types of measures that's probably as simple as totaling all the county/tract values. for others like %s or indices, it's probably more complicated or not relevant. if it's something we need to capture from the ingested data rather than calculate ourselves, we'll have to wait until Faisal is back next week

Summary: make "extra info" checkbox (under "Customization") checked by default, and add "Total" or "Overall" value to the legend along with the min/max/mean/median that's already there. The legend is basically showing overall values (for the whole state of Colorado) for the selected measure.

I could do a total very easily from the frontend, right where I'm already doing the average and median calculations. I could use the "unit type" Faisal added to each measure to only show the total when it makes sense (e.g. "total population" or "cancer mortality -> all cancer sites") and hide it when it doesn't (e.g. "annual labor force participation %").

**Comment by cydneyj303** [comment]
Hi all -

I can't remember the exact details of our last discussion regarding adding state and maybe national averages for cancer incidence, mortality, and some screening/risk factor data. I think I will have to pull the screening/risk factor averages and compile them in a list for you all to add. 

With incidence and mortality, they appear in the downloaded file from SCP. The screenshot shows where these averages are found in that file you would pull from SCP directly. 
![image](https://github.com/user-attachments/assets/9ed6204b-9ffb-477f-b72f-80562215408b)

I know you all had to do some cleaning of these data to get it to input correctly. What is the easiest way to go about this? Are you able to pull these numbers using code, or would it be easier if I compile these averages on a word doc that I then give to you to implement on the map (as I would for the screening data). 

Let me know. Thanks!

**Comment by vincerubinetti** [comment]
Just an update from my perspective. This was partially addressed by https://github.com/colorado-cancer-center/ecco/pull/84, where I just added a simple total to the frontend derived from the data we already have. The simple total is really only valid for certain types of measures that have absolute counts/units. So, getting the totals for _all_ measures will require extra processing and thought, as you mentioned.

**Comment by cydneyj303** [comment]
Hi Vince -

I don't think we need totals. If we can just pull the averages from State Cancer Profiles for all cancers (or just the top ten in CO, which I can provide for you), that would be great. We can find the min/max using the "Extra Info" selection, but averages are what we're looking for for cancer incidence, mortality, and the sociodemographic variables we're interested in. 

What's the best way to go about this? I can provide a document with all those state-wide averages if that's easier than pulling from SCP. I will have to do this for the sociodemographic variables anyways, I think. 

Happy to meet and discuss further if needed :)

**Comment by vincerubinetti** [comment]
Per discussion today, we're just going to manually curate this state value for each measure. This makes it easier for us; now we don't have to do any calculations or complicated if/then checking of the units, we just display the data that was given to us (that other people have done the hard work to ensure accuracy).

This would also be a top-level field on `/fips-value`, I'd imagine. So with all the recent changes discussed, that endpoint return structure would look like: `{ min, max, state_wide, values, unit, order, source }`. Am I missing anything?

**Comment by cydneyj303** [comment]
Attached are averages we discussed during last meeting. 
[ECCO_IncAverages.csv](https://github.com/user-attachments/files/16997890/ECCO_IncAverages.csv)

Incidence and mortality include both a state and national average. Screening and risk factor measures are just state averages. For the screening and risk factors, I included the data source. 

I'm curious to know how close the #s you calculated are to these actual averages. 

Let me know if you have any questions or concerns about the averages I've attached.

**Comment by cydneyj303** [comment]
Averages for incidence, mortality, and screening and risk factors attached. 
[ECCO_IncAverages.xlsx](https://github.com/user-attachments/files/16998102/ECCO_IncAverages.xlsx)


For incidence: state and national averages, including late stage averages here
For mortality: state and national averages, no late stage data available
For screening and risk factors: only state averages; included data sources

Curious to know how close your calculated #s are to these. As always, let me know if you have questions/concerns
