### ISSUE TITLE
Download button not working

### ISSUE THREAD

**Issue by cydneyj303** [colorado-cancer-center/ecco#80]
Not sure if this is only for lung & bronchus, but when we hit download next to the measure, it comes up with a blank Excel. When we hit the download button next to the measure category, the data opens up. Hopefully just an easy bug to fix. Thanks!

![image](https://github.com/colorado-cancer-center/ecco/assets/139499061/4d0fc200-252d-489b-a2f1-998777b8a779)

**Comment by vincerubinetti** [comment]
Should be fixed by https://github.com/colorado-cancer-center/ecco/commit/4b874f60f452249e3b6f03f1dc91c520bc4ff8d0
