### ISSUE TITLE
Map showing a color when it should be showing no data (I think)

### ISSUE THREAD

**Issue by cydneyj303** [colorado-cancer-center/ecco#90]
Hey! I'm playing around with ECCO before my presentation on Wednesday and am noticing that this map is showing a color when it should be grey for "no data." Hopefully you all can double check this and make any changes before the presentation (Wednesday at 11am). No worries if not but wanted to bring this up sooner rather than later. Thank you! 

This is one example.
![image](https://github.com/user-attachments/assets/cb9108b8-3c94-4e93-b991-2d2a0ce21d6d)

**Comment by vincerubinetti** [comment]
Accidental regression in https://github.com/colorado-cancer-center/ecco/blame/main/frontend/src/components/AppMap.vue#L627. The "no data" color is not ever showing.

Fixed in https://github.com/colorado-cancer-center/ecco/commit/aff66121f19b1a6c71cfbb31637018fc940671b3
